name: Continuous Integration
on:
  push:
    branches:
      - main  # Defina a branch onde o workflow será executado (ajuste conforme necessário)

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Esta etapa faz o checkout do seu repositório

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5  # Escolha a versão do Python que deseja usar (por exemplo, 3.8, 3.9, 3.10)

      - name: Install Poetry
        run: |
          pip install poetry==1.6.1
          poetry --version  # Verifica a versão do Poetry

      - name: Install Dependencies
        run: |
          poetry install  # Instala as dependências do projeto com Poetry

      - name: Format
        run: |
          poetry run make format
          
      - name: Run Tests
        run: |
          poetry run make test


